# Generated by Django 5.0.1 on 2024-01-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='cover',
            field=models.ImageField(null=True, upload_to='recipes/covers/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='description',
            field=models.CharField(max_length=165, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='preparation_steps',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='preparation_steps_is_html',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='preparation_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='preparation_time_unit',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='servings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='servings_unit',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='title',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
