# Generated by Django 5.0.1 on 2024-01-24 14:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_name_receipe_category_receipe_cover_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
    ]
